services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - inception_network
    restart: on-failure

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "8081:8081"
      - "666:666"
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: on-failure

  portainer:
    build: ./bonus/portainer
    container_name: portainer
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  redis:
    build: ./bonus/redis
    container_name: redis
    networks:
      - inception_network
    depends_on:
      - wordpress
    volumes:
      - redis_vol:/data

  adminer:
    build: ./bonus/adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception_network

  ftp:
    build: ./bonus/ftp
    container_name: ftp
    restart: always
    volumes:
      - wp_vol:/volume
    env_file:
      - .env
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception_network


volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ratavare/Documents/aaa/data/db_vol
  wp_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ratavare/Documents/aaa/data/wp_vol
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ratavare/Documents/aaa/data/portainer_data
  redis_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ratavare/Documents/aaa/data/redis_vol

networks:
  inception_network:
    name: inception_network
